name: CI Trigger
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: JS testing trigger
        run: |
          curl -X POST https://api.github.com/repos/ToghrulMirzayev/ui-simulator-js-testing/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ToghrulMirzayev:${{ secrets.REPO_ACCESS }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "arst" }}'
      - name: Python testing trigger
        run: |
          curl -X POST https://api.github.com/repos/ToghrulMirzayev/ui-simulator-python-testing/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ToghrulMirzayev:${{ secrets.REPO_ACCESS }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "arst" }}'
