name: Trigger Tests

on:
  push:
    branches:
      - main

jobs:
  trigger_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Regression tests
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS }}
        repository: ToghrulMirzayev/ui-simulator-js-testing
        event-type: run-tests
